cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/


stages:
  - build
  - "create image"
  - "deploy service"


.common_build_template: &common_build_ref
  image: node:11
  before_script:
    - npm install
    - npm install -g @angular/cli grunt
    - grunt copy-hash
    - npm run build
    - grunt revers
  artifacts:
    paths:
      - dist/
    expire_in: 1 day


.deploy_image_branch_template: &deploy_image_branch_ref
  #PARAM
  #DOCKER_IMAGE_TAG - the docker image tag
   image: docker
   stage: "create image"
   before_script:
     - export CI_PROJECT_PATH_LOWERCASE=`echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]'`
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build -f Dockerfile.gitlab-ci -t $CI_REGISTRY/$CI_PROJECT_PATH_LOWERCASE:${DOCKER_IMAGE_TAG} .
     - docker push $CI_REGISTRY/$CI_PROJECT_PATH_LOWERCASE:${DOCKER_IMAGE_TAG}


.deploy_service_template: &deploy_service_ref
  #PARAM
  #ENVIRONMENT_HOST - ip address docker daemon host
   image: docker
   stage: "deploy service"
   cache: {}
   script:
     - export SERVICE_NAME=${CI_COMMIT_REF_NAME}_${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}
     - echo "SERVICE_NAME=$SERVICE_NAME"
     - echo "IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker -H ${ENVIRONMENT_HOST} pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
     - docker -H ${ENVIRONMENT_HOST} service scale $SERVICE_NAME=0
     - docker -H ${ENVIRONMENT_HOST} service update --force $SERVICE_NAME
     - docker -H ${ENVIRONMENT_HOST} service scale $SERVICE_NAME=1


build:
  <<: *common_build_ref
  stage: build
  script:
    - echo build
  only:
    refs:
      - tags
      - test




create image:
  <<: *deploy_image_branch_ref
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME
  only:
      - test

create image tag:
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
  <<: *deploy_image_branch_ref
  only:
    - tags



deploy test:
  <<: *deploy_service_ref
  variables:
    ENVIRONMENT_HOST: 172.32.1.31
  environment:
    name: test
    url: https://test-angular1.jsql.it
  only:
    refs:
      - test
